version: '3.8'

services:
  web:
    build: .
    container_name: python-web
    expose:
      - "5001"
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web